---

- hosts: all
  become: true
  vars:
    newPort: 22
    ansible_port: 22 # change if different than 22
  tasks:
    - name: 'Change SSH port to {{ newPort}}'
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'Port '
        line: 'Port {{ newPort}}'
      register: sshPort

    - name: Install Python3 needed to semanage
      package:
        name:
         - policycoreutils-python-utils
      when:
        ansible_os_family == 'RedHat'

    - name: Add semanage exception
      seport:
        ports: '{{ newPort}}'
        proto: tcp
        setype: ssh_port_t
        state: present
      when:
        sshPort.changed and ansible_os_family == 'RedHat'

    - name: Open port in firewalld
      firewalld:
        port: '{{ newPort}}/tcp'
        permanent: yes
        state: enabled
      when:
        sshPort.changed and ansible_os_family == 'RedHat'

#    - name: Open port in csf
#      firewalld:
#        port: '{{ newPort}}/tcp'
#        permanent: yes
#        state: enabled
#      when:
#        sshPort.changed and ansible_os_family == 'RedHat'

    - name: Restart SSH service in RedHat family
      service:
        name: sshd
        state: restarted
      when:
        sshPort.changed and ansible_os_family == 'RedHat'

    - name: Restart SSH service in Debian family
      service:
        name: ssh
        state: restarted
      when: sshPort.changed and ansible_os_family == 'Debian'
