---
- name: Deploy servers
  hosts: local
  become: true
  roles:
    #- role: alvdev.aliases
    #  become: false
    #  vars:
    #    aliases_user: alvdev

    - role: alvdev.cloudlinux
      vars:
        cloudlinux_key: empty key
        imunify_key: empty key
