---
- name: Deploy servers
  hosts: local
  roles:
    #- role: alvdev.aliases
    #  become: false
    #  vars:
    #    aliases_user: alvdev

    - role: alvdev.cloudlinux
      become: true
      vars:
        cloudlinux_key: empty key
