---
- name: Setup dircolors
  hosts: all
  become: true
  tasks:
    - name: Check if DIR_COLORS file exists on Ubuntu
      ansible.builtin.stat:
        path: /etc/DIR_COLORS
      register: dircolors
    
    #
    # Ubuntu servers don't have DIR_COLORS
    #
    - name: Create DIR_COLORS if doesn't exist
      ansible.builtin.file:
        path: /etc/DIR_COLORS
        owner: root
        group: root
        mode: 0644
      when:
        dircolors.stat.exists

    - name: Add dircolors template to file
      ansible.builtin.shell:
        dircolors -p > /etc/DIR_COLORS
      when:
        dircolors.stat.exists


    - name: Configure colors
      ansible.builtin.blockinfile:
        path: /etc/DIR_COLORS
        marker: "# {mark} ANSIBLE MANAGED BLOCK for dircolors"
        block: |
          OTHER_WRITABLE 04;31;01

    - name: Insert blank line before the marker
      ansible.builtin.lineinfile:
        path: /etc/DIR_COLORS
        insertbefore: "^# BEGIN ANSIBLE MANAGED BLOCK"
        line: ""
