---
- hosts: all
  become: true
  tasks:
    - name: Set grub timeout
      lineinfile:
        path: /etc/default/grub
        regex: '^GRUB_TIMEOUT'
        line: GRUB_TIMEOUT=0
      register: grub

    - name: Regenerate boot grub config (Debian)
      command:
        grub-mkconfig -o /boot/grub/grub.cfg
      when:
        grub.changed and ansible_os_family == 'Debian'

    - name: Regenerate boot grub config (RedHat)
      command:
        grub2-mkconfig -o /boot/grub2/grub.cfg
      when:
        grub.changed and ansible_os_family == 'RedHat'
