---
- name: Change user password
  hosts: all
  become: true
  tasks:
    - name: change password
      user:
        name: alvdev
        update_password: always
        password: "{{ password | password_hash('sha512') }}"

