---
- hosts: all
  become: true
  tasks:
    - name: Create sudo users
      user:
        name: alvdev
        groups: wheel
      when: ansible_os_family == 'RedHat'

    - name: Add ssh key for sudo users
      authorized_key:
        user: alvdev
        key:
          'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdVJumm7Q0pvd3jlZzyrEdiMCP6xX9yCx/iBLr863vkHlvx9NpM3Bkc
          │ Sxc4EBmTeROvsOx3zQ3j24Xh/4S/BKWnOlAEiUHAjtpVR3NQR67LHRP4rRlOviiM+gsxDRtCjcujn8Cbw95aqwKf/Mdli
          │ IJzCvTHkiZzmGSnaaGjsD03+xJ0QopCpZ/4A1V9ZA827pkssTNk95OzvwOB1q1IMnM4ESLlLpRjIvPOILGbUtykIDJwvO
          │ U5lD/fZQuNym9E3ZB1Gq/kNgpoXk32cScTQuoh3Y3ugrW8/ca70kl4L7kmmeTgpoRsHVgB21KfzAc2eYUfpQPdVZNT2NF
          │ 681okytt6L5s9r00SnMi+a/T9h2vFjmrw2X+JRuWKkvUjcGxubNvm4PgFcskc2noUvoa2c24JCfZzwA8IBIhHBOM844Bo
          │ m9e3daMdJ0W1mMhfoq1gIR6cqqIH9BoVk91DGiEoOjC04fxxKaUXJjBCEWbOfon1I5W+aZpJU2DTBr7GHvGhE0= alvde
          │ v@workstation'

    - name: Add sudoer privileges file to /etc/sudoers.d/
      copy:
        dest: /etc/sudoers.d/alvdev
        mode: 0440
        content: |
          alvdev    ALL=(ALL)    NOPASSWD: ALL
