---

- hosts: all
  become: true
  vars:
    vim_user: alvdev
  tasks:
    - name: Install Vim
      package:
        name:
          - vim
        state: latest
      become: true

    - name: Create directory
      file:
        path: "/home/{{ vim_user }}/.vim/autoload"
        owner: "{{ vim_user }}"
        group: "{{ vim_user }}"
        mode: 0755
        recurse: true

    - name: Download vim plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "/home/{{ vim_user }}/.vim/autoload/plug.vim"
        owner: "{{ vim_user }}"
        group: "{{ vim_user }}"
        mode: 0666

    - name: Create .vimrc file if not exists
      file:
        path: '/home/{{ vim_user }}/.vimrc'
        owner: '{{ vim_user }}'
        group: '{{ vim_user }}'
        state: touch

    - name: Insert Vim setup lines 
      blockinfile:
       path: '/home/{{ vim_user }}/.vimrc'
       marker: '" {mark} MANAGED ANSIBLE BLOCK for vim setup'
       block: |
         
         if empty(glob('~/.vim/autoload/plug.vim'))
           silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                 \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
           autocmd VimEnter * PlugInstall | source $MYVIMRC
         endif

         autocmd FileType yml,yaml setlocal ai ts=2 sts=2 sw=2 expandtab
         " Set shift width to 4 spaces.
         set shiftwidth=4
         
         " Set tab width to 4 columns.
         set softtabstop=4
         
         " Use space characters instead of tabs.
         set expandtab
         
         " Do not save backup files.
         set nobackup
         
         " Do not let cursor scroll below or above N number of lines when scrolling.
         set scrolloff=10
         
         " Do not wrap lines. Allow long lines to extend as far as the line goes.
         set nowrap
         
         " While searching though a file incrementally highlight matching characters as you type.
         set incsearch
         
         " Ignore capital letters during search.
         set ignorecase
         
         " Override the ignorecase option if searching for capital letters.
         " This will allow you to search specifically for capital letters.
         set smartcase
         
         " Show partial command you type in the last line of the screen.
         set showcmd
         
         " Show the mode you are on the last line.
         set showmode
         
         " Show matching words during a search.
         set showmatch
         
         " Use highlighting when doing a search.
         set hlsearch
         
         " Set the commands to save in history default number is 20.
         set history=1000
         set nu
         syntax on
         "set cursorline
         set mouse=a
         filetype on
         filetype indent on
         
         " Enable auto completion menu after pressing TAB.
         set wildmenu
         
         " Make wildmenu behave like similar to Bash completion.
         set wildmode=list:longest
         
         " There are certain files that we would never want to edit with Vim.
         " Wildmenu will ignore files with these extensions.
         set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
         
         """ Plugins
         call plug#begin()
         
         " html
         Plug 'mattn/emmet-vim'
         Plug 'alvan/vim-closetag'
         Plug 'AndrewRadev/tagalong.vim'

         " css
         Plug 'ap/vim-css-color'
         Plug 'hail2u/vim-css3-syntax'
         
         " js
         Plug 'pangloss/vim-javascript'
         Plug 'elzr/vim-json'
         Plug 'prettier/vim-prettier'

         Plug 'sonph/onehalf', { 'rtp': 'vim' }
         
         call plug#end()
         
         """ THEME SECTION
         
         " Set colorscheme
         colorscheme onehalfdark
         highlight Normal ctermbg=none
         highlight LineNr ctermfg=darkgrey ctermbg=none
         
         " status bar colors
         au InsertEnter * hi statusline cterm=bold ctermfg=black ctermbg=yellow
         au InsertLeave * hi statusline cterm=bold ctermfg=white ctermbg=darkgrey
         hi statusline cterm=bold ctermfg=white ctermbg=darkgrey
         
         " Status line
         " default: set statusline=%f\ %h%w%m%r\ %=%(%l,%c%V\ %=\ %P%)
         
         " Status Line Custom
         let g:currentmode={
             \ 'n'  : 'Normal',
             \ 'no' : 'Normal·Operator Pending',
             \ 'v'  : 'Visual',
             \ 'V'  : 'V·Line',
             \ '^V' : 'V·Block',
             \ 's'  : 'Select',
             \ 'S'  : 'S·Line',
             \ '^S' : 'S·Block',
             \ 'i'  : 'Insert',
             \ 'R'  : 'Replace',
             \ 'Rv' : 'V·Replace',
             \ 'c'  : 'Command',
             \ 'cv' : 'Vim Ex',
             \ 'ce' : 'Ex',
             \ 'r'  : 'Prompt',
             \ 'rm' : 'More',
             \ 'r?' : 'Confirm',
             \ '!'  : 'Shell',
             \ 't'  : 'Terminal'
             \}
         
         set laststatus=2
         set noshowmode
         set statusline=
         set statusline+=%0*\ %{toupper(g:currentmode[mode()])}\  " The current mode
         set statusline+=%1*\ %<%F%m%r%h%w\                       " File path, modified, readonly, helpfile, preview
         set statusline+=%3*│                                     " Separator
         set statusline+=%2*\ %Y\                                 " FileType
         set statusline+=%3*│                                     " Separator
         set statusline+=%2*\ %{''.(&fenc!=''?&fenc:&enc).''}     " Encoding
         set statusline+=\ (%{&ff})                               " FileFormat (dos/unix..)
         set statusline+=%=                                       " Right Side
         set statusline+=%2*\ col:\ %02v\                         " Colomn number
         set statusline+=%3*│                                     " Separator
         set statusline+=%1*\ ln:\ %02l/%L\ (%3p%%)\              " Line number / total lines, percentage of document
         set statusline+=%0*\ %n\                                 " Buffer number
         
         
         hi User1 ctermfg=007 ctermbg=239 guibg=#4e4e4e guifg=#adadad
         hi User2 ctermfg=007 ctermbg=236 guibg=#303030 guifg=#adadad
         hi User3 ctermfg=236 ctermbg=236 guibg=#303030 guifg=#303030
         hi User4 ctermfg=239 ctermbg=239 guibg=#4e4e4e guifg=#4e4e4e
