---
- name: Install services
  hosts: local
  vars:
    - services_items:
      - "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
  tasks:
    - name: Install service on RedHat based systems
      dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        "{{ services_items }}"
      when:
        ansible_os_family == "RedHat"
    
    - name: Install service on Debian based systems
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        "{{ services_items }}"
      when:
        ansible_os_family == "Debian"

