---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: alma8-base
    image: almalinux/8-base
    pre_build_image: true

  - name: ubuntu
    image: ubuntu
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
