---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: alma8
    image: almalinux/8-base
    pre_build_image: true

  - name: ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
