---

tasks:
  #
  # bashrc file section
  #
  - name: Check if .bashrc exists
    stat:
      path: '{{ ansible_env.PWD }}/.bashrc'
    register: bashrc

  - name: Add code to .bashrc file if exists
    blockinfile:
      path: '{{ ansible_env.PWD }}/.bashrc'
      marker: '# {mark} ANSIBLE MANAGED BLOCK for custom alias file'
      block: |
        if [ -f ~/.aliases ]; then
          . ~/.aliases
        fi
    when: bashrc.stat.exists

  - name: Insert blank line before the marker
    lineinfile:
      path: '{{ ansible_env.PWD }}/.bashrc'
      insertbefore: '^# BEGIN ANSIBLE MANAGED BLOCK'
      line: ''
  
  #
  # zshrc file section
  #
  - name: Check if .zshrc exists
    stat:
      path: '{{ ansible_env.PWD }}/.zshrc'
    register: zshrc

  - name: Add code to .zshrc file if exists
    blockinfile:
      path: '{{ ansible_env.PWD }}/.zshrc'
      marker: '# {mark} ANSIBLE MANAGED BLOCK for custom alias file'
      block: |
        if [ -f ~/.aliases ]; then
          . ~/.aliases
        fi
    when: zshrc.stat.exists
  
  #
  # Alias file section
  #
  - name: Check if .alias file exists
    stat:
      path: '{{ ansible_env.PWD }}/.aliases'
    register: alias

  - name: Create .aliases file
    file:
      path: '{{ ansible_env.PWD }}/.aliases'
      state: touch
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
    when: not alias.stat.exists
  
  - name: Setup custom aliases
    blockinfile:
      path: '{{ ansible_env.PWD }}/.aliases'
      marker: '# {mark} ANSIBLE MANAGED BLOCK for custom alias'
      block: |
        {{ aliases }}
