---
- name: Check CloudLinux installation
  ansible.builtin.stat:
    path: /usr/bin/cldetect
  register: cldetect

- name: CloudLinux installation status
  ansible.builtin.debug:
    msg: "CloudLinux is already installed"
  when: cldetect.stat.exists
  failed_when: cldetect.stat.exists

- name: Continue installation
  ansible.builtin.include_tasks:
    install-cloudlinux.yml
