---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    privileged: yes
    override_command: false

#  - name: ubuntu20
#    image: alehaa/debian-systemd
#    privileged: true
#    #override_command: false
#    pre_build_image: true
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
#  - name: debian10
#    image: mpaivabarbosa/molecule-systemd-debian:10
#    #image: mesaguy/ansible-molecule-debian
#    #volumes:
#    #  - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    privileged: true
#    pre_build_image: true
#    override_command: false
#    #command: /lib/systemd/systemd --user

#  - name: ubuntu18
#    image: solita/ubuntu-systemd:18.04
#    privileged: true
#    override_command: false
#    pre_build_image: true

provisioner:
  name: ansible
  #config_options:
  #  defaults:
  #    interpreter_python: auto_silent
  #    #callback_whitelist: profile_tasks, timer, yaml
  #  ssh_connection:
  #    pipelining: false
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
